Use fullname for resources (i.e. services)
Currently, Prometheus and Grafana can't be installed together in one
release, because the name of `server` services overlap themselves.

```yaml
dependencies:
  - name: prometheus
    version: 2.0.2
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: 0.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
```

```
$ helm install .
Created tunnel using local port: '53637'
SERVER: "localhost:53637"
CHART PATH: /var/folders/4q/nz4ytb693fzf70m5wcqk5ldc0000gn/T/tmp.4Rhs39DEiQ
Error: release insipid-zorse failed: services "insipid-zorse-server" already exists
```